version: "3.9"

services:
    micro_02:
        build:
            args:
                user: marco
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - microservice02

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservice02

    microzerodois:
        image: mysql:5.7
        container_name: microzerodois
        tty: true
        environment:
            MYSQL_DATABASE: 'microzerodois'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3308:3306"
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - microservice02

networks:
    microservice02:
        driver: bridge
